<?php

namespace TestBundle\Repository;
use TestBundle\Entity\Etat;
use TestBundle\DQL;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCriteres($nom = null, $prenom = null,$etat = null,$mois = null,$annee = null){
        $qb = $this->createQueryBuilder('f')->join('f.visiteur','v');



        if ($nom != null){
            $qb->where("v.nom = :nom");
            $qb->setParameter('nom', $nom);
        }

        if ($prenom != null){
            $qb->andWhere("v.prenom = :prenom");
            $qb->setParameter('prenom', $prenom);
        }

        if ($mois != null){
            $qb->andWhere("MONTH(f.Mois) = :mois");
            $qb->setParameter("mois",$mois);
        }

        if ($annee != null){
            $qb->andWhere("YEAR(f.Mois) = :annee");
            $qb->setParameter("annee",$annee);
        }

        if ($etat != null){
            $qb->andwhere("f.etat = :etat");
            $qb->setParameter('etat', $etat);
        }



        if ($nom == null && $prenom == null && $etat == null && $mois == null && $annee == null) return null;

        return $qb->getQuery()->getResult();
    }
}
