<?php

namespace TestBundle\Repository;

/**
 * FraisForfaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisForfaisRepository extends \Doctrine\ORM\EntityRepository
{
}
