<?php

namespace TestBundle\Repository;

/**
 * LigneForfaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneForfaisRepository extends \Doctrine\ORM\EntityRepository
{
}
