<?php

namespace TestBundle\Repository;

/**
 * LigneHorForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneHorForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
