<?php

namespace Proxies\__CG__\TestBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LigneForfais extends \TestBundle\Entity\LigneForfais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'id', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'quantite', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'fichefrai', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'FraisForfais', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'date', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'montant', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'valide'];
        }

        return ['__isInitialized__', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'id', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'quantite', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'fichefrai', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'FraisForfais', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'date', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'montant', '' . "\0" . 'TestBundle\\Entity\\LigneForfais' . "\0" . 'valide'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LigneForfais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFichefrai(\TestBundle\Entity\FicheFrais $fichefrai = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichefrai', [$fichefrai]);

        return parent::setFichefrai($fichefrai);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichefrai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichefrai', []);

        return parent::getFichefrai();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisForfais(\TestBundle\Entity\FraisForfais $fraisForfais = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisForfais', [$fraisForfais]);

        return parent::setFraisForfais($fraisForfais);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisForfais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisForfais', []);

        return parent::getFraisForfais();
    }

    /**
     * {@inheritDoc}
     */
    public function setValide($valide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValide', [$valide]);

        return parent::setValide($valide);
    }

    /**
     * {@inheritDoc}
     */
    public function getValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValide', []);

        return parent::getValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantite($quantite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantite', [$quantite]);

        return parent::setQuantite($quantite);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantite', []);

        return parent::getQuantite();
    }

}
