<?php

namespace Proxies\__CG__\TestBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheFrais extends \TestBundle\Entity\FicheFrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'nombreJustificatif', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'Mois', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'dateCreation', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'justificatif', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'visiteur', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'LigneForFais', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'LigneHorForFait'];
        }

        return ['__isInitialized__', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'nombreJustificatif', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'Mois', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'dateCreation', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'justificatif', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'visiteur', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'LigneForFais', '' . "\0" . 'TestBundle\\Entity\\FicheFrais' . "\0" . 'LigneHorForFait'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheFrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombreJustificatif($nombreJustificatif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreJustificatif', [$nombreJustificatif]);

        return parent::setNombreJustificatif($nombreJustificatif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreJustificatif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreJustificatif', []);

        return parent::getNombreJustificatif();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantValide($montantValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantValide', [$montantValide]);

        return parent::setMontantValide($montantValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantValide', []);

        return parent::getMontantValide();
    }

    /**
     * {@inheritDoc}
     */
    public function addJustificatif(\TestBundle\Entity\Justificatif $justificatif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJustificatif', [$justificatif]);

        return parent::addJustificatif($justificatif);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJustificatif(\TestBundle\Entity\Justificatif $justificatif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJustificatif', [$justificatif]);

        return parent::removeJustificatif($justificatif);
    }

    /**
     * {@inheritDoc}
     */
    public function getJustificatif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJustificatif', []);

        return parent::getJustificatif();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(\TestBundle\Entity\Etat $etat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneForFai(\TestBundle\Entity\LigneForfais $ligneForFai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneForFai', [$ligneForFai]);

        return parent::addLigneForFai($ligneForFai);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneForFai(\TestBundle\Entity\LigneForfais $ligneForFai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneForFai', [$ligneForFai]);

        return parent::removeLigneForFai($ligneForFai);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneForFais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneForFais', []);

        return parent::getLigneForFais();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisiteur(\TestBundle\Entity\Visiteur $visiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisiteur', [$visiteur]);

        return parent::setVisiteur($visiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisiteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisiteur', []);

        return parent::getVisiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneHorForFait(\TestBundle\Entity\LigneHorForfait $ligneHorForFait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneHorForFait', [$ligneHorForFait]);

        return parent::addLigneHorForFait($ligneHorForFait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneHorForFait(\TestBundle\Entity\LigneHorForfait $ligneHorForFait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneHorForFait', [$ligneHorForFait]);

        return parent::removeLigneHorForFait($ligneHorForFait);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneHorForFait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneHorForFait', []);

        return parent::getLigneHorForFait();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($dateModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', [$dateModif]);

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', []);

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function updateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateDate', []);

        return parent::updateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMois($mois)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMois', [$mois]);

        return parent::setMois($mois);
    }

    /**
     * {@inheritDoc}
     */
    public function getMois()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMois', []);

        return parent::getMois();
    }

}
